# About the data



Metadata Exploration:
   
    1. Who assembled this data, and why?
    - Bonanza Creek Experimental Forest to analyze the fluctuation of the Snowshoe hares population because they are a 'keystone' prey species in northern boreal forests.
    
    2. What does a single row in the data represent?
    - A moment where a Hare was captured and biometric data was captured about the individual.
   
    3. When and where were the observations collected?
    - Bonanza Creek Experimental Forest, in a specific boundary box from 1999 to present.
  
    4. Does the dataset contain sensitive data?
    -no
   
    5. What study protocols were used to collect the data?
    - Capture and release
   
    6. What are the units for the hares’ weight?
    -grams
   
    7. Does the metadata say how missing data is encoded?
    -no
  
    8. Is there a publication associated with this dataset?
    - no

Citation:Kielland, K., F.S. Chapin, R.W. Ruess, and Bonanza Creek LTER. 2017. Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present ver 22. Environmental Data Initiative. https://doi.org/10.6073/pasta/03dce4856d79b91557d8e6ce2cbcdc14 (Accessed 2026-10-16). 

Date of access: 2026-10-15

Archive link:www.lter.uaf.edu/data/data-detail/id/55 

Potential issues: 
- There is missing data in every column, that could lead to sparse analysis or inability to capture the full story of what is occuring. As this is a continued project, there could be inconsistencies in the way data is collected when there are changes of participants, especially if there is not a strict protocol detailed for those conducting the research. If protocols, method of collection, or other aspeccts change it could could cause othere inconsistencies, even if it is better for the project as a whole.

![image description](https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/1920px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20170313021652)

In [1]:
# Import libraries
import pandas as pd 
import os 
import numpy as np

In [2]:
hare = pd.read_csv("data/55_Hare_Data_2012.txt")

In [11]:
hare.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3380 entries, 0 to 3379
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        3380 non-null   object
 1   time        264 non-null    object
 2   grid        3380 non-null   object
 3   trap        3368 non-null   object
 4   l_ear       3332 non-null   object
 5   r_ear       3211 non-null   object
 6   sex         3028 non-null   object
 7   age         1269 non-null   object
 8   weight      2845 non-null   float64
 9   hindft      1633 non-null   float64
 10  notes       243 non-null    object
 11  b_key       3333 non-null   float64
 12  session_id  3380 non-null   int64
 13  study       3217 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 369.8+ KB

In [4]:
hare.shape

(3380, 14)

In [10]:
hare.isna()

       date   time   grid   trap  l_ear  r_ear    sex   age  weight  hindft  notes  b_key  session_id  study
0     False   True  False  False  False   True   True  True   False   False   True  False       False  False
1     False   True  False  False  False   True  False  True   False    True   True  False       False  False
2     False   True  False  False  False   True  False  True   False    True   True  False       False  False
3     False   True  False  False  False   True   True  True   False   False   True  False       False  False
4     False   True  False  False  False   True   True  True   False   False   True  False       False  False
...     ...    ...    ...    ...    ...    ...    ...   ...     ...     ...    ...    ...         ...    ...
3375  False  False  False  False  False  False   True  True   False    True   True  False       False  False
3376  False  False  False  False  False  False   True  True    True    True   True  False       False  False
3377  False   True  False  False  False  False   True  True   False   False   True  False       False  False
3378  False   True  False  False  False  False   True  True   False    True   True  False       False  False
3379  False   True  False  False  False  False  False  True   False   False   True  False       False  False

[3380 rows x 14 columns]

In [7]:
hare.describe()

            weight       hindft        b_key   session_id
count  2845.000000  1633.000000  3333.000000  3380.000000
mean   1346.081547   130.872627   500.640864    53.232249
std     345.160112    16.155295   299.421121    33.171355
min       0.000000    60.000000     1.000000     1.000000
25%    1180.000000   128.000000   235.000000    22.000000
50%    1400.000000   135.000000   464.000000    55.000000
75%    1580.000000   140.000000   755.000000    82.000000
max    2365.000000   160.000000  1034.000000   113.000000

In [9]:
hare.nunique()

date           256
time           165
grid             5
trap           121
l_ear         1020
r_ear          963
sex             12
age             30
weight         266
hindft          90
notes          118
b_key         1026
session_id     113
study            4
dtype: int64